// AUTO-GENERATED by scripts/generate-locales.mjs — do not edit.
// Run `npm run gen:locales` to refresh. Source: Optimizely CMS Management API /locales.

export type Locale = {
  /** BCP-47 language tag, e.g. "en", "es", "sv-SE". */
  key: string;
  /** Human-readable name shown in the language switcher. */
  displayName: string;
  /** URL segment for routing. Empty string for the default locale (clean URLs). */
  routeSegment: string;
};

export const DEFAULT_LOCALE = "en";

export const LOCALES: Locale[] = [
  {
    "key": "en",
    "displayName": "English",
    "routeSegment": ""
  },
  {
    "key": "sv",
    "displayName": "svenska",
    "routeSegment": "sv"
  }
];
